dist: trusty
sudo: false
language: node_js

node_js:
  - "8"
  - "9"
  - "10"

# Need to support c++17
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  - CXX=g++-7

branches:
  only:
    - master

# Install scripts (runs after repo cloning).
install:
  - npm install --build-from-source

# Post-install test scripts.
script:
  # Run tests.
  - npm test

# Bundle a node-pre-gyp package.
after_success:
  - npm run package

deploy:
  provider: releases
  draft: true
  api_key:
    secure: aLX4m46Wbg6r1bYmSeTKslxZWEqnI7pmdVMbx8G/4JQdaQy2ut0INjpg1BQKl9lHtN4+hDgAXdKZ1qUN3G/ZIbWDfy76n+O6FdRCMr5wpL99RCxpfrDmpUg8lp0c6R27pxnX50Nwwak1SXXZICbceTdDNAhiieCfS/7GGW1XO08USGvTUgbQejQkGsM35Zx53bs5Je5HyyGTEBuu6pPACo9tB/geHsRhJMb40q6cC7vqwdTcIo2iaqJJAWk9oIqovdVv+aYWsGXe9LP7fVxBnkg1Lf6d929pLY+d6TGd0V9+Qf5BAtxk1yB0rDRH6ea4I8tM+ViYks9OmSldLrVFKFuB6HsZ3DJAJz0gNk0cW16dXOmYL44olKwvDiIuXhmB8KJ6R5uoDw6xulIbr2KtRSjb0KfFzXhYqjbqd3ssoX7PSeUQnbcl/RHYmQFUgRsfTARBJlqSsNsiPE5zEHUM5z6XgVMBX2dc5S29KY0ojO8EfebapcRWFNVonMSkmmIVDtpzpRmsqzEEMbJz00Nz39RO8LEt7sQOolYMwWFCDzn1pIrNOYIwKdV4bjkbNUbusoqsJehUdLiiu6DCXGc7ByKscW4R4hhUGTGb7CSKCnDGPk1UFpYH8QeAU5um+kg/seujkbdyf3dMbZoyQgqGBln02D58dzq3ICvIJB7BFdo=
  file_glob: true
  file: build/stage/**/maluubaspeech*.tar.gz
  skip_cleanup: true
  on:
    tags: true
