environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"

platform:
  - x86
  - x64

branches:
  only:
    - master

# Install scripts (runs after repo cloning).
install:
  # Get git submodules.
  - git submodule update --init --recursive
  # Get Node.js.
  - ps: Install-Product node $env:nodejs_version $env:platform
  # Install Node.js modules.
  - npm install --build-from-source

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Run tests.
  - npm test

# Bundle a node-pre-gyp package.
after_test:
  - npm run package

# node-pre-gyp artifacts.
artifacts:
  - path: build/stage/**/maluubaspeech*.tar.gz

# Need cl to support c++17.
image: Visual Studio 2017

# Turn off msbuild phase.
build: off
